version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8082:8082"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins

networks:
  default:
    external:
      name: bridge
